[platformio]
default_envs = attiny1614

[env:attiny1614]
platform = atmelmegaavr
board = ATtiny1614

; Bare-metal register-level C (own main()).
board_build.f_cpu = 3333333L
build_flags =
    -DF_CPU=3333333UL
    -Wall
    -Wextra
    -std=c11

; UPDI upload on PA0 via serial UPDI programmer.
upload_protocol = custom
upload_port = COM4
upload_speed = 230400
upload_command = avrdude -p t1614 -c serialupdi -P $UPLOAD_PORT -b $UPLOAD_SPEED -U flash:w:$SOURCE:i
